FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:99

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget \
        gnupg \
        ca-certificates \
        curl \
        software-properties-common \
        build-essential \
        libnss3 \
        libatk1.0-0 \
        libatk-bridge2.0-0 \
        libcups2 \
        libdrm2 \
        libxcomposite1 \
        libxrandr2 \
        libgbm1 \
        libasound2 \
        libpangocairo-1.0-0 \
        libgtk-3-0 \
        xvfb \
        x11-utils \
        x11-apps \
        libx11-xcb1 \
        libxcb-dri3-0 \
        libxshmfence1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxinerama1 \
        libxkbcommon-x11-0 \
        libxrender1 \
        libxtst6 \
        libappindicator3-1 \
        xauth \
        ffmpeg \
        fonts-unifont \
        fonts-ubuntu \
        unzip \
        lsof \
        psmisc \
        xauth \
        netpbm \
        postgresql \
        postgresql-contrib \
        postgresql-client \
        && rm -rf /var/lib/apt/lists/* \
        && apt-get clean

WORKDIR /app

# Install Python 3.11 + dev headers
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.11 python3.11-dev python3.11-tk

# Set Python 3.11 as the default python and python3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.11 1 && \
    update-alternatives --set python /usr/bin/python3.11 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1 && \
    update-alternatives --set python3 /usr/bin/python3.11 && \
    apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install --upgrade pip


RUN apt-get remove python3-blinker -y
RUN pip install blinker==1.7.0

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

RUN playwright install-deps
RUN playwright install

ENV PYTHONPATH="/app:${PYTHONPATH}"

COPY collector /app/collector
COPY evaluation /app/evaluation
COPY run.sh /app/run.sh

# Add LiteLLM installation
#RUN pip install litellm

# Copy LiteLLM config
#COPY litellm_custom_groq_config.yaml /app/litellm_custom_groq_config.yaml

# Add startup script
#COPY start_services.sh /app/start_services.sh
#RUN chmod +x /app/start_services.sh

# Update entrypoint
#CMD ["/app/start_services.sh"]