VALIDATION_RULES = {
    "skyvern": {
        "required": ["site", "task"],
        "allowed": [
            "site",
            "task",
            "text",
            "agent_method",
            "timeout",
            "site_category",
            "darkpattern_category",
            "real-site",
        ],
    },
    "webarena": {
        "required": ["site", "task"],
        "allowed": [
            "site",
            "task",
            "text",
            "agent_method",
            "timeout",
            "site_category",
            "darkpattern_category",
            "real-site",
        ],
    },
    "visualwebarena": {
        "required": ["site", "task"],
        "allowed": [
            "site",
            "task",
            "text",
            "agent_method",
            "timeout",
            "site_category",
            "darkpattern_category",
            "real-site",
        ],
    },
    "human": {
        "required": ["site", "task"],
        "allowed": [
            "site",
            "task",
            "simulate_ios",
            "text",
            "use_cookies",
            "agent_method",
            "timeout",
            "concurrency",
            "total_tasks",
            "site_category",
            "darkpattern_category",
        ],
    },
    "multion": {
        "required": ["site", "task"],
        "allowed": [
            "site",
            "task",
            "has_adblocker",
            "no-has-adblocker",
            "text",
            "use_cookies",
            "agent_method",
            "timeout",
            "concurrency",
            "total_tasks",
            "site_category",
            "darkpattern_category",
        ],
    },
    "dobrowser": {
        "required": ["site", "task"],
        "allowed": [
            "site",
            "task",
            "has_adblocker",
            "no-has-adblocker",
            "text",
            "use_cookies",
            "agent_method",
            "timeout",
            "concurrency",
            "total_tasks",
            "site_category",
            "darkpattern_category",
        ],
    },
    "browseruse": {
        "required": ["site", "task"],
        "allowed": [
            "site",
            "task",
            "text",
            "agent_method",
            "timeout",
            "site_category",
            "darkpattern_category",
            "real-site",
        ],
    },
    "agente": {
        "required": ["site", "task"],
        "allowed": [
            "site",
            "task",
            "text",
            "agent_method",
            "timeout",
            "site_category",
            "darkpattern_category",
            "real-site",
        ],
    }
}
